# Generated by Django 6.0.3 on 2026-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysense', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='buysense_pr_created_d6d607_idx'),
        ),
    ]
